/*script structure bdd site_btp*/

CREATE TABLE CATEGORIE (
    CA_Ref INTEGER NOT NULL AUTO_INCREMENT,
    CA_Nom VARCHAR(40),
    CA_RefParent INTEGER,
	
    PRIMARY KEY (CA_Ref)
)
ENGINE=INNODB;

ALTER TABLE CATEGORIE
ADD CONSTRAINT FK_Categ FOREIGN KEY (CA_RefParent) REFERENCES CATEGORIE(CA_Ref);

CREATE TABLE ARTICLE (
    AR_Ref VARCHAR(255) NOT NULL,
    AR_Design VARCHAR(40),
    AR_Sommeil BOOLEAN,
    AR_DateCreation DATETIME,
    AR_Etat VARCHAR(40),
    AR_DateDernierEntretien DATE,
	AR_DateDerniereReparation DATE,
	CA_Ref INTEGER,

    PRIMARY KEY (AR_Ref),
	FOREIGN KEY (CA_Ref) REFERENCES CATEGORIE(CA_Ref)
)
ENGINE=INNODB;


CREATE TABLE UTILISATEUR (
    UT_Ref INTEGER NOT NULL AUTO_INCREMENT,
    UT_Mail VARCHAR(40),
    UT_Nom VARCHAR(40),
    UT_Prenom VARCHAR(40),
    UT_Type INTEGER,
    UT_DateCreation DATE,
	UT_Password VARCHAR(255),
	UT_Sommeil BOOLEAN,
	UT_Uniqld VARCHAR(40),

    PRIMARY KEY (UT_Ref)
)
ENGINE=INNODB;


CREATE TABLE EMPLACEMENT (
    EM_Ref INTEGER NOT NULL AUTO_INCREMENT,
    EM_Intitule VARCHAR(40),
    EM_Type INTEGER,
	
    PRIMARY KEY (EM_Ref)
)
ENGINE=INNODB;


CREATE TABLE SUIVI (
    SU_Id INTEGER NOT NULL AUTO_INCREMENT,
    AR_Ref VARCHAR(255),
	EM_Ref INTEGER,
    UT_Ref INTEGER,
	SU_DateMouvement DATETIME,
	
    PRIMARY KEY (SU_Id)
)
ENGINE=INNODB;


CREATE TABLE ETAT (
    ET_Ref VARCHAR(40),
    ET_Intitule VARCHAR(40),
	
    PRIMARY KEY (ET_Ref)
)
ENGINE=INNODB;

ALTER TABLE ARTICLE
ADD FOREIGN KEY (AR_Etat) REFERENCES ETAT(ET_Ref);

CREATE TABLE COMPTE (
    CO_Ref INTEGER,
    CO_Intitule VARCHAR(255),
	
    PRIMARY KEY (CO_Ref)
)
ENGINE=INNODB;

ALTER TABLE UTILISATEUR
ADD FOREIGN KEY (UT_Type) REFERENCES COMPTE(CO_Ref);

ALTER TABLE EMPLACEMENT
ADD EM_DateDebut DATETIME,

ALTER TABLE EMPLACEMENT
ADD EM_DateFin DATETIME,

ALTER TABLE SUIVI
ADD FOREIGN KEY (AR_Ref) REFERENCES ARTICLE(AR_Ref);

ALTER TABLE SUIVI
ADD FOREIGN KEY (EM_Ref) REFERENCES EMPLACEMENT(EM_Ref);

ALTER TABLE SUIVI
ADD FOREIGN KEY (UT_Ref) REFERENCES UTILISATEUR(UT_Ref);


